---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pappasam/toml-sort.git
      rev: v0.23.1
      hooks:
          - id: toml-sort
            args: [--in-place, --all, --ignore-case]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.10.1
      hooks:
          - id: pyupgrade
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.2.0
      hooks:
          - id: pycln
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black, --filter-files, --combine-as]
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.4.1
      hooks:
          - id: mypy
            additional_dependencies:
                - pydantic
                - types-requests
